- blocks/hero/hero.css
- blocks/hero/hero.js
- blocks/search/worker.js
Fix #7
- Before: https://main--vg-roadchoice-com--volvogroup.aem.page/drafts/shomps/hero
- After: https://7-hero-block--vg-roadchoice-com--volvogroup.aem.page/drafts/shomps/hero
- Before: https://main--roadchoice-ca--volvogroup.aem.page/drafts/shomps/hero
- After: https://7-hero-block--roadchoice-ca--volvogroup.aem.page/drafts/shomps/hero
- Before: https://main--roadchoice-mx--volvogroup.aem.page/drafts/shomps/hero
- After: https://7-hero-block--roadchoice-mx--volvogroup.aem.page/drafts/shomps/hero
> Hero Block #7

- package.json
> Update develop from main pre-release

- head.html
Fix bug
- After: https://FIX-revert-head-change--vg-roadchoice-com--volvogroup.aem.page/
> Revert preload

- blocks/hero/hero.css
- blocks/hero/hero.js
- icons/pause-video.svg
- icons/play-video.svg
- scripts/video-helper.js
- styles/styles.css
Fix #11
- Before: https://main--vg-roadchoice-com--volvogroup.aem.page/drafts/shomps/hero-video
- After: https://11-video-in-hero--vg-roadchoice-com--volvogroup.aem.page/drafts/shomps/hero-video
> Video implementation in hero #11

- blocks/category-filters/category-filters.js
- blocks/category-pagination/category-pagination.js
- blocks/category-results-list/category-results-list.js
- blocks/columns/columns.js
- blocks/dealer-locator/sidebar-maps.js
- blocks/pdp/pdp.js
- blocks/recommendations/recommendations.js
- blocks/results-list/product-card.js
- blocks/search/search.js
- blocks/search/worker.js
- scripts/common.js
- scripts/scripts.js
- templates/part-category/part-category.js
Fix #53
Fix #56
- After: https://56-multilang-content-requests--vg-roadchoice-com--volvogroup.aem.page/
- After: https://56-multilang-content-requests--roadchoice-ca--volvogroup.aem.page/
- After: https://56-multilang-content-requests--roadchoice-mx--volvogroup.aem.page/
> Multi language content requests #56

- scripts/delayed.js
Fix #84 
- After: https://84-maze-integration--vg-roadchoice-com--volvogroup.aem.page/
- After: https://84-maze-integration--roadchoice-ca--volvogroup.aem.page/
> Maze Integration for User Experience Testing on Road Choice #84

- blocks/breadcrumb/breadcrumb.css
- templates/part-category/part-category.js
Fix #25
- Before: https://main--vg-roadchoice-com--volvogroup.aem.page/part-category/?category=s-cams
- After: https://25-hyphen-missing-product--vg-roadchoice-com--volvogroup.aem.page/part-category/?category=s-cams
> Hyphen is either missing or deleted in product names #25

- blocks/breadcrumb/breadcrumb.css
- package-lock.json
- package.json
- scripts/delayed.js
- templates/part-category/part-category.js
- After: https://release-12--vg-roadchoice-com--volvogroup.aem.page/
- After: https://release-12--roadchoice-ca--volvogroup.aem.page/
- After: https://release-12--roadchoice-mx--volvogroup.aem.page/
> Release 12

- blocks/v2-custom-form/responses/error.js
- blocks/v2-custom-form/responses/success.js
- blocks/v2-custom-form/v2-custom-form.css
- blocks/v2-custom-form/v2-custom-form.js
- common/custom-dropdown/custom-dropdown.css
- common/custom-dropdown/custom-dropdown.js
- placeholder.json
Fix #121
- Before: https://main--vg-roadchoice-com--volvogroup.aem.page/block-library/blocks/v2-custom-form
- After: https://121-mcae-forms--vg-roadchoice-com--volvogroup.aem.page/block-library/blocks/v2-custom-form
> Create New Block for Marketing Cloud Account Engagement Forms - RC #121

- blocks/header/header.css
- styles/styles.css
Fix #38 
- After: https://38-wider-mega-menu-columns--vg-roadchoice-com--volvogroup.aem.page/
- After: https://38-wider-mega-menu-columns--roadchoice-ca--volvogroup.aem.page/
- After: https://38-wider-mega-menu-columns--roadchoice-mx--volvogroup.aem.page/
> CR: Make columns wider on Categories mega-menu dropdown #38

- blocks/header/header.css
- blocks/pagination/pagination.js
- constants.json
- package-lock.json
- package.json
- placeholder.json
- styles/styles.css
- After: https://release-14--vg-roadchoice-com--volvogroup.aem.page/
- After: https://release-14--roadchoice-ca--volvogroup.aem.page/
- After: https://release-14--roadchoice-mx--volvogroup.aem.page/
> Release 14

- blocks/v2-custom-form/v2-custom-form.css
- blocks/v2-custom-form/v2-custom-form.js
Fix #137
- Before: https://main--vg-roadchoice-com--volvogroup.aem.page/drafts/shomps/form/v2-custom-form
- After: https://137-2-column-form--vg-roadchoice-com--volvogroup.aem.page/drafts/shomps/form/v2-custom-form
>  FR: Double Column Variant Form for the MCAE - RC #137

- blocks/category-results-list/category-results-list.js
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #159
- Before: https://main--vg-roadchoice-com--volvogroup.aem.page/part-category/?category=clamps
- After: https://159-allow-new-img-sources--vg-roadchoice-com--volvogroup.aem.page/part-category/?category=clamps
> FR: Change Base URL of image library #159

- blocks/v2-custom-form/v2-custom-form.css
- blocks/v2-custom-form/v2-custom-form.js
- package-lock.json
- package.json
- After: https://release-16--vg-roadchoice-com--volvogroup.aem.page/
> Release 16

- blocks/pdp/pdp.js
- blocks/search/autosuggest-helper.js
- blocks/search/graphql-api.js
- blocks/search/search.css
- blocks/search/search.js
- constants.json
- package-lock.json
- package.json
- placeholder.json
- After: https://release-18--vg-roadchoice-com--volvogroup.aem.page/
- After: https://release-18--roadchoice-ca--volvogroup.aem.page/
- After: https://release-18--roadchoice-mx--volvogroup.aem.page/
> Release 18

- blocks/search/search.js
Fix #190
- After: https://190-empty-results-with-null--vg-roadchoice-com--volvogroup.aem.page/
> Bug: Fixed null issue in search query

- blocks/blog-results/blog-results.css
- blocks/category-filters/category-filters.css
- blocks/footer/footer.css
- blocks/search/search.css
- blocks/v2-custom-form/v2-custom-form.css
- icons/pause-video.svg
- icons/play-video.svg
- styles/styles.css
Fix #9
- Before: https://main--vg-roadchoice-com--volvogroup.aem.page/drafts/shomps/testing-page
- After: https://9-buttons--vg-roadchoice-com--volvogroup.aem.page/drafts/shomps/testing-page
- After: https://9-buttons--roadchoice-ca--volvogroup.aem.page/
- After: https://9-buttons--roadchoice-mx--volvogroup.aem.page/
> FR: Updating Button Design #9

- blocks/iframe/iframe.css
- blocks/iframe/iframe.js
- blocks/pdp/pdp.js
- blocks/search/search.js
- package.json
- After: https://release-20--vg-roadchoice-com--volvogroup.aem.page/
- After: https://release-20--roadchoice-ca--volvogroup.aem.page/
- After: https://release-20--roadchoice-mx--volvogroup.aem.page/
> Release 20

- blocks/results-list/product-card.js
Fix #237
- Before: https://main--vg-roadchoice-com--volvogroup.aem.page/parts?category=grilles&sku=GRL91080
- After: https://237-rc-part-description--vg-roadchoice-com--volvogroup.aem.page/parts/grilles/GRL91080/
> Bug: No product description displayed after clicking search result #237

- .github/workflows/publish-notifier.yaml
> FR: Terraform Infrastructure for Categories Ingestion Lambda #223

- .github/workflows/blog-publish-notifier.yaml
- .github/workflows/blog-unpublish-notifier.yaml
[FR: Create GitHub action for ingestion](https://github.com/aemsites/vg-roadchoice-com/issues/230)
Fix #230
> Feature/#230 fr create GitHub action for ingestion

- .github/workflows/blog-publish-notifier.yaml
- .github/workflows/blog-unpublish-notifier.yaml
Please always provide the [FR: Create GitHub action for ingestion](https://github.com/aemsites/vg-roadchoice-com/issues/230) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #230 
> Remove .md from path

- .github/workflows/blog-publish-notifier.yaml
- .github/workflows/blog-unpublish-notifier.yaml
Please always provide the [FR: Create GitHub action for ingestion](https://github.com/aemsites/vg-roadchoice-com/issues/230) your PR is for, as well as test URLs where your change can be observed (before and after):
Fix #230 
> Update startswith to contains

- .github/workflows/publish-notifier.yaml
Issue: FR: Implement multi-tenancy on the ingestion Lambdas
[#276](https://github.com/aemsites/vg-roadchoice-com/issues/276)
> FR: Implement multi-tenancy on the ingestion Lambdas #276
